### ISSUE TITLE
about chinese

### ISSUE THREAD

**Issue by Goodahome** [MGeurts/genealogy#15]
Did I affect your code? Because I saw that you improved Chinese and then removed,I'm sorry,I once modified the code according to the way Chinese people use it. Thank you for your open source.I want help you to finish your project,but my skills are poor,I will help you translate chinese,I will not modify the code.  https://fmy.gooda.homes/

**Comment by MGeurts** [comment]
No problem. At first, I saw your Chinese translation and wanted to integrate it because China has over 1 billion people. But then I decided to not rely on translation services like Google Translate and to only manage languages I speak myself.

**Comment by MGeurts** [comment]
Hi Goodahome,

If you want to add the Chinese language (like for instance **zh_CN** for mainland China), then you could **create a Pull Request**:

1. create a folder /lang/zh_CN/
2. copy all files from /lang/en/ to /lang/zh_CN/
3. translate all files in /lang/zh_CN/

Please use simplified characters.

Then I will integrate the Chinese language.

Thanks.

**Comment by Goodahome** [comment]
okay
