### ISSUE TITLE
about ancestors & descendants chart

### ISSUE THREAD

**Issue by Goodahome** [MGeurts/genealogy#16]
![image](https://github.com/user-attachments/assets/347ac36b-f716-43d9-9690-527609620bb4)
Can there be a page that can show the structure diagram of the whole family, instead of targeting a person's ancestors and descendants?

**Comment by MGeurts** [comment]
If you go to the **family root person** and then set the level counter to maximum, you'll get the whole tree.

![Naamloos](https://github.com/user-attachments/assets/9e2befee-91a0-4c92-9997-156dda43bfe2)

**Comment by Goodahome** [comment]
I mean if can click one button then will see all people,Have you considered adding a spouse's family? Then there will be multiple root people.

**Comment by MGeurts** [comment]
Including the spouses is a very difficult task to accomplish. The current algorythms for getting the ascendants and descendants uses Recursive Common Table Expressions (MySQL). This technique only allows 1 root for every subtree.

**Comment by Goodahome** [comment]
Okay,thanks

**Comment by MGeurts** [comment]
But I'll keep looking for a solution...
