### ISSUE TITLE
Add new language (Vietnamese)

### ISSUE THREAD

**Issue by diepdo1810** [MGeurts/genealogy#21]
Hi.

I checked and couldn't find Vietnamese. I would like to contribute by adding a language.

**Comment by MGeurts** [comment]
Hi. Please create a Pull Request containing all files in [https://github.com/MGeurts/genealogy/tree/main/lang/en](https://github.com/MGeurts/genealogy/tree/main/lang/en) translated to Vietnamese. The folder shoud be named **/vi/**. Thanks.
