### ISSUE TITLE
 language options : "chinese" is wrong

### ISSUE THREAD

**Issue by Goodahome** [MGeurts/genealogy#25]
![image](https://github.com/user-attachments/assets/8620bf05-accc-411e-a8ad-46222ed0e9a0)

it shoud be “中文简体”

**Comment by MGeurts** [comment]
Corrected.

Please also check:

1. [https://genealogy.kreaweb.be/about](https://genealogy.kreaweb.be/about)
2. [https://genealogy.kreaweb.be/terms-of-service](https://genealogy.kreaweb.be/terms-of-service)
3. [https://genealogy.kreaweb.be/privacy-policy](https://genealogy.kreaweb.be/privacy-policy)

Are those pages readable to you?

Thanks for your support!

**Comment by Goodahome** [comment]
yes，I have deployed software，I saw some incorrect words

**Comment by Goodahome** [comment]
![image](https://github.com/user-attachments/assets/6bd6d940-1b09-4a9c-886c-79901ac120eb)

**Comment by Goodahome** [comment]
what`s your email ? can i add your facebook or another ? I want talk with you 
![3BD63964](https://github.com/user-attachments/assets/a41727c6-7531-4ea3-8bc5-f6604b92280e)

**Comment by MGeurts** [comment]
info@kreaweb.be
