### ISSUE TITLE
GEDCOM import

### ISSUE THREAD

**Issue by iPublicis** [MGeurts/genealogy#6]
On GEDCOM import you may wish to look at https://github.com/liberu-genealogy/genealogy-laravel

**Comment by iPublicis** [comment]
Also https://github.com/cgdsoftware/laravel-gedcom

**Comment by MGeurts** [comment]
Thank you. I know those resources.

But kindly only open Issues for real issues.
Use [Discussions](https://github.com/MGeurts/genealogy/discussions) for anything else.
