### ISSUE TITLE
would be good to actually have installation manual,  

### ISSUE THREAD

**Issue by TaKeOVER15** [MGeurts/genealogy#8]
there is no details to install this properly,

**Comment by MGeurts** [comment]
What property do you mean?
Are you using this in a Docker environment?
If yes, I'll have to remove the Docker configuration because it was added by another contributor and I don't use nor know Docker so I can not maintain this way of using the application.

**Comment by MGeurts** [comment]
I removed the Docker configuration files because they were provided by another user and not used nor maintained by me.
If you want to use this application in a Docker enveronment, please fork the project and set it up yourself.
