### ISSUE TITLE
sail error

### ISSUE THREAD

**Issue by TaKeOVER15** [MGeurts/genealogy#9]
./vendor/bin/sail artisan key:generate

   UnexpectedValueException 

  The stream or file "/var/www/html/storage/logs/laravel-2024-08-23.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: file_put_contents(/var/www/html/.env): Failed to open stream: Permission denied
Context: {"exception":{}}

  at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:140
    136▕             }
    137▕             if (!\is_resource($stream)) {
    138▕                 $this->stream = null;
    139▕ 
  ➜ 140▕                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url) . Utils::getRecordMessageForException($record));
    141▕             }
    142▕             stream_set_chunk_size($stream, $this->streamChunkSize);
    143▕             $this->stream = $stream;
    144▕         }

      +13 vendor frames 

  14  artisan:13
      Illuminate\Foundation\Application::handleCommand()

**Comment by MGeurts** [comment]
What did you do exactly to trigger this error?

**Comment by MGeurts** [comment]
This error only occures in a Docker environment.
I removed the Docker configuration files because they were provided by another user and not used nor maintained by me.
If you want to use this application in a Docker enveronment, please fork the project and set it up yourself.

**Comment by TaKeOVER15** [comment]
it was run in a ubuntu lcx container, not the docker installation, so how do i actually install this?
